Repository airr-community/airr-standards, pull requests merged in 2020-01, with the labels that each got.

#304 cell and nucleic_acid comment update
  lang/R/inst/extdata/airr-schema.yaml
  lang/python/airr/specs/airr-schema.yaml
  specs/airr-schema.yaml
Labels: ADC API V1, AIRRv1.3

#282 Add locus x-airr extensions
  lang/R/inst/extdata/airr-schema.yaml
  lang/python/airr/specs/airr-schema.yaml
  specs/airr-schema.yaml
Labels: ADC API V1, AIRRv1.3

#296 Fix and harmonize ontologies
  lang/R/inst/extdata/airr-schema.yaml
  lang/python/airr/specs/airr-schema.yaml
  specs/airr-schema.yaml
Labels: AIRRv1.3, Ontology

#294 minimal clones and trees schema for initial release
  lang/R/inst/extdata/airr-schema.yaml
  lang/python/airr/specs/airr-schema.yaml
  specs/airr-schema.yaml
  specs/immunedb-clones.yaml
  specs/olmsted-airr-schema.yaml
Labels: AIRRv1.3

#251 clones and trees schema
  lang/R/inst/extdata/airr-schema.yaml
  lang/python/airr/specs/airr-schema.yaml
  specs/airr-schema.yaml
Labels: AIRRv1.3

#315 Fields for IMGT support
  docs/datarep/alignments.rst
  docs/datarep/rearrangements.rst
  docs/miairr/vdjserver.rst
  lang/R/inst/extdata/airr-schema.yaml
  lang/python/airr/specs/airr-schema.yaml
  specs/airr-schema.yaml
Labels: AIRRv1.3
